2021-08-26 19:11:03,096 INFO    MainThread:7780 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 19:11:03,096 INFO    MainThread:7780 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 19:11:03,097 INFO    MainThread:7780 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 19:11:03,097 INFO    MainThread:7780 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210826_191103-1o1jgfti\logs\debug.log
2021-08-26 19:11:03,097 INFO    MainThread:7780 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210826_191103-1o1jgfti\logs\debug-internal.log
2021-08-26 19:11:03,098 INFO    MainThread:7780 [wandb_init.py:init():375] calling init triggers
2021-08-26 19:11:03,130 INFO    MainThread:7780 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-26 19:11:03,130 INFO    MainThread:7780 [wandb_init.py:init():395] re-initializing run, found existing run on stack: z0nozawk
2021-08-26 19:11:03,130 INFO    MainThread:7780 [wandb_run.py:finish():1254] finishing run khushal/pipweather-recognization/z0nozawk
2021-08-26 19:11:03,131 INFO    MainThread:7780 [jupyter.py:save_history():339] not saving jupyter history
2021-08-26 19:11:03,131 INFO    MainThread:7780 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 19:11:03,131 INFO    MainThread:7780 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-26 19:11:03,131 INFO    MainThread:7780 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-26 19:11:03,132 INFO    MainThread:7780 [wandb_run.py:_restore():1526] restore
2021-08-26 19:11:03,197 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-08-26 19:11:03,772 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-08-26 19:11:04,511 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-08-26 19:11:05,127 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,228 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,329 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,431 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,532 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,634 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,736 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,838 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:05,940 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19923
}

2021-08-26 19:11:06,042 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,143 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,245 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,372 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,479 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,600 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:06,701 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:07,210 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:07,311 INFO    MainThread:7780 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19923
  total_bytes: 19923
}

2021-08-26 19:11:08,685 INFO    MainThread:7780 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-26 19:11:08,687 INFO    MainThread:7780 [wandb_run.py:_show_history():1869] rendering history
2021-08-26 19:11:08,689 INFO    MainThread:7780 [wandb_run.py:_show_files():1898] logging synced files
2021-08-26 19:11:08,695 INFO    MainThread:7780 [wandb_init.py:init():424] starting backend
2021-08-26 19:11:08,695 INFO    MainThread:7780 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-26 19:11:08,700 INFO    MainThread:7780 [backend.py:ensure_launched():135] starting backend process...
2021-08-26 19:11:08,835 INFO    MainThread:7780 [backend.py:ensure_launched():139] started backend process with pid: 11596
2021-08-26 19:11:08,836 INFO    MainThread:7780 [wandb_init.py:init():429] backend started and connected
2021-08-26 19:11:08,837 INFO    MainThread:7780 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-26 19:11:08,837 INFO    MainThread:7780 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-26 19:11:08,837 INFO    MainThread:7780 [wandb_init.py:init():477] updated telemetry
2021-08-26 19:11:08,838 INFO    MainThread:7780 [wandb_init.py:init():500] communicating current version
2021-08-26 19:11:12,553 INFO    MainThread:7780 [wandb_init.py:init():505] got version response 
2021-08-26 19:11:12,553 INFO    MainThread:7780 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-26 19:11:13,139 INFO    MainThread:7780 [wandb_init.py:init():540] starting run threads in backend
2021-08-26 19:11:18,152 INFO    MainThread:7780 [wandb_run.py:_console_start():1584] atexit reg
2021-08-26 19:11:18,153 INFO    MainThread:7780 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-26 19:11:18,153 INFO    MainThread:7780 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-26 19:11:18,156 INFO    MainThread:7780 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-26 19:11:18,156 INFO    MainThread:7780 [wandb_init.py:init():565] run started, returning control to user process
2021-08-26 19:37:59,853 INFO    MainThread:7780 [wandb_run.py:finish():1254] finishing run khushal/pipweather-recognization/1o1jgfti
