2021-08-18 19:10:55,616 INFO    MainThread:280 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 19:10:55,616 INFO    MainThread:280 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 19:10:55,617 INFO    MainThread:280 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_191055-1xhbwy6v\logs\debug.log
2021-08-18 19:10:55,617 INFO    MainThread:280 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_191055-1xhbwy6v\logs\debug-internal.log
2021-08-18 19:10:55,619 INFO    MainThread:280 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001F3388537F0>
2021-08-18 19:10:55,619 INFO    MainThread:280 [wandb_init.py:init():375] calling init triggers
2021-08-18 19:10:55,620 INFO    MainThread:280 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 19:10:55,621 INFO    MainThread:280 [wandb_init.py:init():424] starting backend
2021-08-18 19:10:55,621 INFO    MainThread:280 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 19:10:55,636 INFO    MainThread:280 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 19:10:56,007 INFO    MainThread:280 [backend.py:ensure_launched():139] started backend process with pid: 11696
2021-08-18 19:10:56,008 INFO    MainThread:280 [wandb_init.py:init():429] backend started and connected
2021-08-18 19:10:56,009 INFO    MainThread:280 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 19:10:56,011 INFO    MainThread:280 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 19:10:56,011 INFO    MainThread:280 [wandb_init.py:init():477] updated telemetry
2021-08-18 19:10:56,013 INFO    MainThread:280 [wandb_init.py:init():500] communicating current version
2021-08-18 19:11:01,013 INFO    MainThread:280 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 19:11:01,931 INFO    MainThread:280 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 19:11:06,957 INFO    MainThread:280 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 19:11:06,959 INFO    MainThread:280 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 19:11:06,960 INFO    MainThread:280 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 19:11:06,965 INFO    MainThread:280 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 19:11:06,965 INFO    MainThread:280 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 19:11:06,966 INFO    MainThread:280 [wandb_config.py:__setitem__():141] config set epochs = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001F339701640>>
2021-08-18 19:11:06,966 INFO    MainThread:280 [wandb_run.py:_config_callback():826] config_cb epochs 50 None
2021-08-18 19:11:10,378 INFO    MainThread:280 [wandb_config.py:__setitem__():141] config set dropout = 0.2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001F339701640>>
2021-08-18 19:11:10,378 INFO    MainThread:280 [wandb_run.py:_config_callback():826] config_cb dropout 0.2 None
2021-08-18 19:38:54,457 INFO    MainThread:280 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 19:38:54,458 INFO    MainThread:280 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 19:41:23,955 INFO    MainThread:280 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 19:41:24,137 INFO    MainThread:280 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 19:41:24,137 INFO    MainThread:280 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 19:41:53,129 INFO    MainThread:280 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 19:41:53,131 INFO    MainThread:280 [wandb_run.py:_restore():1526] restore
2021-08-18 19:41:53,570 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 19:41:54,543 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 19:41:55,508 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:55,614 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:55,742 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:55,848 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:55,953 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,057 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,161 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,263 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,368 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,469 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,572 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,677 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,780 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,883 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 27532
}

2021-08-18 19:41:56,985 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,090 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,193 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,296 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,399 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,502 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,635 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:57,739 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:58,322 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:58,494 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:41:58,598 INFO    MainThread:280 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 27532
  total_bytes: 27532
}

2021-08-18 19:42:01,690 INFO    MainThread:280 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-18 19:42:01,692 INFO    MainThread:280 [wandb_run.py:_show_history():1869] rendering history
2021-08-18 19:42:01,694 INFO    MainThread:280 [wandb_run.py:_show_files():1898] logging synced files
