2021-09-04 14:50:40,181 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_145040-1gjkk0p2\logs\debug.log
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_145040-1gjkk0p2\logs\debug-internal.log
2021-09-04 14:50:40,183 INFO    MainThread:24248 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023AB5504BB0>
2021-09-04 14:50:40,211 INFO    MainThread:24248 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_init.py:init():395] re-initializing run, found existing run on stack: e9wjig9g
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_run.py:finish():1271] finishing run khushal/final-weather-recognization/e9wjig9g
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-04 14:50:40,213 INFO    MainThread:24248 [wandb_run.py:_restore():1543] restore
2021-09-04 14:50:40,756 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:50:41,406 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:50:42,248 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,349 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,450 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,551 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,652 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,753 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,854 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20170
}

2021-09-04 14:50:42,955 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 857
  total_bytes: 20170
}

2021-09-04 14:50:43,056 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,157 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,258 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,359 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,460 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,561 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:43,662 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:44,582 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:44,683 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20170
  total_bytes: 20170
}

2021-09-04 14:50:46,052 INFO    MainThread:24248 [wandb_run.py:_show_files():1915] logging synced files
2021-09-04 14:50:46,056 INFO    MainThread:24248 [wandb_init.py:init():424] starting backend
2021-09-04 14:50:46,057 INFO    MainThread:24248 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-04 14:50:46,061 INFO    MainThread:24248 [backend.py:ensure_launched():135] starting backend process...
2021-09-04 14:50:46,199 INFO    MainThread:24248 [backend.py:ensure_launched():139] started backend process with pid: 15520
2021-09-04 14:50:46,200 INFO    MainThread:24248 [wandb_init.py:init():429] backend started and connected
2021-09-04 14:50:46,200 INFO    MainThread:24248 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-04 14:50:46,200 INFO    MainThread:24248 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-04 14:50:46,201 INFO    MainThread:24248 [wandb_init.py:init():477] updated telemetry
2021-09-04 14:50:46,201 INFO    MainThread:24248 [wandb_init.py:init():500] communicating current version
2021-09-04 14:50:49,435 INFO    MainThread:24248 [wandb_init.py:init():505] got version response 
2021-09-04 14:50:49,435 INFO    MainThread:24248 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-04 14:50:50,142 INFO    MainThread:24248 [wandb_init.py:init():540] starting run threads in backend
2021-09-04 14:50:55,157 INFO    MainThread:24248 [wandb_run.py:_console_start():1601] atexit reg
2021-09-04 14:50:55,161 INFO    MainThread:24248 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-04 14:50:55,161 INFO    MainThread:24248 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-04 14:50:55,164 INFO    MainThread:24248 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-04 14:50:55,164 INFO    MainThread:24248 [wandb_init.py:init():565] run started, returning control to user process
2021-09-04 14:51:31,222 INFO    MainThread:24248 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-04 14:51:31,223 INFO    MainThread:24248 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-04 14:53:03,390 INFO    MainThread:24248 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-04 14:53:03,484 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:53:03,485 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:53:03,485 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:53:03,486 INFO    MainThread:24248 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_145303-ldniw0bp\logs\debug.log
2021-09-04 14:53:03,487 INFO    MainThread:24248 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_145303-ldniw0bp\logs\debug-internal.log
2021-09-04 14:53:03,489 INFO    MainThread:24248 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:53:03,506 INFO    MainThread:24248 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:53:03,506 INFO    MainThread:24248 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1gjkk0p2
2021-09-04 14:53:03,507 INFO    MainThread:24248 [wandb_run.py:finish():1271] finishing run khushal/final-weather-recognization/1gjkk0p2
