2021-08-18 11:13:12,227 INFO    MainThread:16152 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 11:13:12,227 INFO    MainThread:16152 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 11:13:12,227 INFO    MainThread:16152 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_111312-2y3zu1q7\logs\debug.log
2021-08-18 11:13:12,227 INFO    MainThread:16152 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_111312-2y3zu1q7\logs\debug-internal.log
2021-08-18 11:13:12,227 INFO    MainThread:16152 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B7A8D39250>
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_init.py:init():375] calling init triggers
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_init.py:init():395] re-initializing run, found existing run on stack: pnv26zb8
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/pnv26zb8
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 11:13:12,259 INFO    MainThread:16152 [wandb_run.py:_restore():1526] restore
2021-08-18 11:13:12,994 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 11:13:13,145 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 11:13:13,919 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 11:13:14,815 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:14,925 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,034 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,144 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,253 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,362 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,472 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,581 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,690 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,800 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:15,909 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 23372
}

2021-08-18 11:13:16,019 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,128 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,237 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,347 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,456 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,565 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:16,675 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:17,688 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:17,797 INFO    MainThread:16152 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23372
  total_bytes: 23372
}

2021-08-18 11:13:19,533 INFO    MainThread:16152 [wandb_run.py:_show_files():1898] logging synced files
2021-08-18 11:13:19,533 INFO    MainThread:16152 [wandb_init.py:init():424] starting backend
2021-08-18 11:13:19,533 INFO    MainThread:16152 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 11:13:19,549 INFO    MainThread:16152 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 11:13:19,829 INFO    MainThread:16152 [backend.py:ensure_launched():139] started backend process with pid: 13556
2021-08-18 11:13:19,833 INFO    MainThread:16152 [wandb_init.py:init():429] backend started and connected
2021-08-18 11:13:19,836 INFO    MainThread:16152 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 11:13:19,836 INFO    MainThread:16152 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 11:13:19,836 INFO    MainThread:16152 [wandb_init.py:init():477] updated telemetry
2021-08-18 11:13:19,838 INFO    MainThread:16152 [wandb_init.py:init():500] communicating current version
2021-08-18 11:13:24,853 INFO    MainThread:16152 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 11:13:27,210 INFO    MainThread:16152 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 11:13:32,252 INFO    MainThread:16152 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 11:13:32,255 INFO    MainThread:16152 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 11:13:32,255 INFO    MainThread:16152 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 11:13:32,262 INFO    MainThread:16152 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 11:13:32,262 INFO    MainThread:16152 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 11:13:32,263 INFO    MainThread:16152 [wandb_config.py:__setitem__():141] config set epochs = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001B7A005F340>>
2021-08-18 11:13:32,263 INFO    MainThread:16152 [wandb_run.py:_config_callback():826] config_cb epochs 50 None
2021-08-18 11:13:55,995 INFO    MainThread:16152 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 11:13:55,995 INFO    MainThread:16152 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 11:13:56,107 INFO    MainThread:16152 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 11:13:56,108 INFO    MainThread:16152 [wandb_run.py:_restore():1526] restore
