2021-08-25 11:48:18,734 INFO    MainThread:14120 [wandb_setup.py:_flush():69] setting env: {}
2021-08-25 11:48:18,734 INFO    MainThread:14120 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-25 11:48:18,735 INFO    MainThread:14120 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210825_114818-2cguct60\logs\debug.log
2021-08-25 11:48:18,735 INFO    MainThread:14120 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210825_114818-2cguct60\logs\debug-internal.log
2021-08-25 11:48:18,736 INFO    MainThread:14120 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001C58A2821C0>
2021-08-25 11:48:18,757 INFO    MainThread:14120 [wandb_init.py:init():375] calling init triggers
2021-08-25 11:48:18,758 INFO    MainThread:14120 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-25 11:48:18,758 INFO    MainThread:14120 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1i9pmz21
2021-08-25 11:48:18,758 INFO    MainThread:14120 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/1i9pmz21
2021-08-25 11:48:18,759 INFO    MainThread:14120 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-25 11:48:18,759 INFO    MainThread:14120 [wandb_run.py:_restore():1526] restore
2021-08-25 11:48:23,118 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
}
pusher_stats {
}

2021-08-25 11:48:23,263 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 476
}

2021-08-25 11:48:24,018 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 476
}

2021-08-25 11:48:25,005 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,108 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,212 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,316 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,419 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,523 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,628 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,732 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,846 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:25,950 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19223
}

2021-08-25 11:48:26,054 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 857
  total_bytes: 19223
}

2021-08-25 11:48:26,158 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6627
  total_bytes: 19223
}

2021-08-25 11:48:26,262 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19196
  total_bytes: 19223
}

2021-08-25 11:48:26,365 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,467 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,571 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,674 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,778 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,882 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:26,986 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:27,539 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:27,642 INFO    MainThread:14120 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19223
  total_bytes: 19223
}

2021-08-25 11:48:29,281 INFO    MainThread:14120 [wandb_run.py:_show_files():1898] logging synced files
2021-08-25 11:48:29,290 INFO    MainThread:14120 [wandb_init.py:init():424] starting backend
2021-08-25 11:48:29,290 INFO    MainThread:14120 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-25 11:48:29,300 INFO    MainThread:14120 [backend.py:ensure_launched():135] starting backend process...
2021-08-25 11:48:29,548 INFO    MainThread:14120 [backend.py:ensure_launched():139] started backend process with pid: 17304
2021-08-25 11:48:29,550 INFO    MainThread:14120 [wandb_init.py:init():429] backend started and connected
2021-08-25 11:48:29,552 INFO    MainThread:14120 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-25 11:48:29,553 INFO    MainThread:14120 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-25 11:48:29,553 INFO    MainThread:14120 [wandb_init.py:init():477] updated telemetry
2021-08-25 11:48:29,555 INFO    MainThread:14120 [wandb_init.py:init():500] communicating current version
2021-08-25 11:48:34,557 INFO    MainThread:14120 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-25 11:48:37,379 INFO    MainThread:14120 [wandb_init.py:init():540] starting run threads in backend
2021-08-25 11:48:42,414 INFO    MainThread:14120 [wandb_run.py:_console_start():1584] atexit reg
2021-08-25 11:48:42,416 INFO    MainThread:14120 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-25 11:48:42,416 INFO    MainThread:14120 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-25 11:48:42,423 INFO    MainThread:14120 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-25 11:48:42,424 INFO    MainThread:14120 [wandb_init.py:init():565] run started, returning control to user process
2021-08-25 11:48:42,647 INFO    MainThread:14120 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-25 11:48:42,647 INFO    MainThread:14120 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-25 11:49:28,064 INFO    MainThread:14120 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-25 11:49:28,066 INFO    MainThread:14120 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-25 11:49:28,067 INFO    MainThread:14120 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-25 11:49:33,596 INFO    MainThread:14120 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-25 11:49:33,598 INFO    MainThread:14120 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-25 11:49:33,598 INFO    MainThread:14120 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-25 11:49:41,563 INFO    MainThread:14120 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-25 11:49:41,582 INFO    MainThread:14120 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-25 11:49:41,583 INFO    MainThread:14120 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-25 11:49:51,076 INFO    MainThread:14120 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-25 11:49:51,086 INFO    MainThread:14120 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-25 11:49:51,086 INFO    MainThread:14120 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-25 11:49:55,191 INFO    MainThread:14120 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-25 11:49:55,375 INFO    MainThread:14120 [wandb_setup.py:_flush():69] setting env: {}
2021-08-25 11:49:55,375 INFO    MainThread:14120 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-25 11:49:55,376 INFO    MainThread:14120 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210825_114955-3jwm83z9\logs\debug.log
2021-08-25 11:49:55,377 INFO    MainThread:14120 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210825_114955-3jwm83z9\logs\debug-internal.log
2021-08-25 11:49:55,379 INFO    MainThread:14120 [wandb_init.py:init():375] calling init triggers
2021-08-25 11:49:55,380 INFO    MainThread:14120 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-25 11:49:55,404 INFO    MainThread:14120 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2cguct60
2021-08-25 11:49:55,404 INFO    MainThread:14120 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/2cguct60
