2021-08-19 01:57:42,691 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting env: {}
2021-08-19 01:57:42,691 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-19 01:57:42,692 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-19 01:57:42,693 INFO    MainThread:9752 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210819_015742-2ia6y6qo\logs\debug.log
2021-08-19 01:57:42,693 INFO    MainThread:9752 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210819_015742-2ia6y6qo\logs\debug-internal.log
2021-08-19 01:57:42,695 INFO    MainThread:9752 [wandb_init.py:init():375] calling init triggers
2021-08-19 01:57:42,699 INFO    MainThread:9752 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-19 01:57:42,700 INFO    MainThread:9752 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3mz2c0m4
2021-08-19 01:57:42,700 INFO    MainThread:9752 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/3mz2c0m4
2021-08-19 01:57:42,701 INFO    MainThread:9752 [jupyter.py:save_history():339] not saving jupyter history
2021-08-19 01:57:42,701 INFO    MainThread:9752 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-19 01:57:42,702 INFO    MainThread:9752 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-19 01:57:42,702 INFO    MainThread:9752 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-19 01:57:42,703 INFO    MainThread:9752 [wandb_run.py:_restore():1526] restore
2021-08-19 01:57:47,331 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
}
pusher_stats {
}

2021-08-19 01:57:47,488 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 484
}

2021-08-19 01:57:48,170 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 484
}

2021-08-19 01:57:48,874 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19738
}

2021-08-19 01:57:48,983 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,086 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,190 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,294 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,398 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,503 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,607 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,711 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,854 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:49,957 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:50,061 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:50,164 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:50,267 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19765
}

2021-08-19 01:57:50,370 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,473 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,577 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,680 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,783 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,888 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:50,991 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:51,094 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:51,199 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:51,718 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:51,822 INFO    MainThread:9752 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19765
  total_bytes: 19765
}

2021-08-19 01:57:53,511 INFO    MainThread:9752 [wandb_run.py:_show_files():1898] logging synced files
2021-08-19 01:57:53,521 INFO    MainThread:9752 [wandb_init.py:init():424] starting backend
2021-08-19 01:57:53,522 INFO    MainThread:9752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-19 01:57:53,531 INFO    MainThread:9752 [backend.py:ensure_launched():135] starting backend process...
2021-08-19 01:57:53,802 INFO    MainThread:9752 [backend.py:ensure_launched():139] started backend process with pid: 17452
2021-08-19 01:57:53,804 INFO    MainThread:9752 [wandb_init.py:init():429] backend started and connected
2021-08-19 01:57:53,806 INFO    MainThread:9752 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-19 01:57:53,806 INFO    MainThread:9752 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-19 01:57:53,806 INFO    MainThread:9752 [wandb_init.py:init():477] updated telemetry
2021-08-19 01:57:53,808 INFO    MainThread:9752 [wandb_init.py:init():500] communicating current version
2021-08-19 01:57:58,810 INFO    MainThread:9752 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-19 01:58:00,842 INFO    MainThread:9752 [wandb_init.py:init():540] starting run threads in backend
2021-08-19 01:58:05,872 INFO    MainThread:9752 [wandb_run.py:_console_start():1584] atexit reg
2021-08-19 01:58:05,899 INFO    MainThread:9752 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-19 01:58:05,900 INFO    MainThread:9752 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-19 01:58:05,905 INFO    MainThread:9752 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-19 01:58:05,906 INFO    MainThread:9752 [wandb_init.py:init():565] run started, returning control to user process
2021-08-19 01:58:05,907 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set epochs = 60 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,907 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb epochs 60 None
2021-08-19 01:58:05,908 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,909 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb size 128 None
2021-08-19 01:58:05,910 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,911 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb dropout 0.3 None
2021-08-19 01:58:05,912 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set batch_size = 14 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,912 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb batch_size 14 None
2021-08-19 01:58:05,913 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set pool_size = [3, 3] - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,913 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb pool_size [3, 3] None
2021-08-19 01:58:05,914 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set shear_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,914 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb shear_range 0.4 None
2021-08-19 01:58:05,914 INFO    MainThread:9752 [wandb_config.py:__setitem__():141] config set zoom_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000268C1C99C10>>
2021-08-19 01:58:05,914 INFO    MainThread:9752 [wandb_run.py:_config_callback():826] config_cb zoom_range 0.4 None
2021-08-19 01:59:02,528 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting env: {}
2021-08-19 01:59:02,528 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-19 01:59:02,529 INFO    MainThread:9752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-19 01:59:02,529 INFO    MainThread:9752 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210819_015902-2hi0oqaa\logs\debug.log
2021-08-19 01:59:02,530 INFO    MainThread:9752 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210819_015902-2hi0oqaa\logs\debug-internal.log
2021-08-19 01:59:02,531 INFO    MainThread:9752 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000268C1B9FF70>
2021-08-19 01:59:02,545 INFO    MainThread:9752 [wandb_init.py:init():375] calling init triggers
2021-08-19 01:59:02,545 INFO    MainThread:9752 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-19 01:59:02,545 INFO    MainThread:9752 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2ia6y6qo
2021-08-19 01:59:02,546 INFO    MainThread:9752 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/2ia6y6qo
