2021-08-24 02:15:00,508 INFO    MainThread:1584 [wandb_setup.py:_flush():69] setting env: {}
2021-08-24 02:15:00,508 INFO    MainThread:1584 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-24 02:15:00,508 INFO    MainThread:1584 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210824_021500-3sr6g6zq\logs\debug.log
2021-08-24 02:15:00,509 INFO    MainThread:1584 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210824_021500-3sr6g6zq\logs\debug-internal.log
2021-08-24 02:15:00,510 INFO    MainThread:1584 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000014E0746D0A0>
2021-08-24 02:15:00,532 INFO    MainThread:1584 [wandb_init.py:init():375] calling init triggers
2021-08-24 02:15:00,532 INFO    MainThread:1584 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-24 02:15:00,532 INFO    MainThread:1584 [wandb_init.py:init():395] re-initializing run, found existing run on stack: txflrv6r
2021-08-24 02:15:00,533 INFO    MainThread:1584 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/txflrv6r
2021-08-24 02:15:00,533 INFO    MainThread:1584 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-24 02:15:00,534 INFO    MainThread:1584 [wandb_run.py:_restore():1526] restore
2021-08-24 02:15:00,729 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-08-24 02:15:01,419 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-08-24 02:15:02,245 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19348
}

2021-08-24 02:15:02,349 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,452 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,555 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,658 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,761 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,862 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:02,966 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19458
}

2021-08-24 02:15:03,068 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 967
  total_bytes: 19458
}

2021-08-24 02:15:03,171 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:03,274 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:03,376 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:03,483 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:03,587 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:03,691 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:04,750 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:04,853 INFO    MainThread:1584 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 19458
  total_bytes: 19458
}

2021-08-24 02:15:06,283 INFO    MainThread:1584 [wandb_run.py:_show_summary():1831] rendering summary
2021-08-24 02:15:06,285 INFO    MainThread:1584 [wandb_run.py:_show_history():1869] rendering history
2021-08-24 02:15:06,287 INFO    MainThread:1584 [wandb_run.py:_show_files():1898] logging synced files
2021-08-24 02:15:06,295 INFO    MainThread:1584 [wandb_init.py:init():424] starting backend
2021-08-24 02:15:06,295 INFO    MainThread:1584 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-24 02:15:06,300 INFO    MainThread:1584 [backend.py:ensure_launched():135] starting backend process...
2021-08-24 02:15:06,453 INFO    MainThread:1584 [backend.py:ensure_launched():139] started backend process with pid: 3344
2021-08-24 02:15:06,455 INFO    MainThread:1584 [wandb_init.py:init():429] backend started and connected
2021-08-24 02:15:06,457 INFO    MainThread:1584 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-24 02:15:06,457 INFO    MainThread:1584 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-24 02:15:06,457 INFO    MainThread:1584 [wandb_init.py:init():477] updated telemetry
2021-08-24 02:15:06,458 INFO    MainThread:1584 [wandb_init.py:init():500] communicating current version
2021-08-24 02:15:10,213 INFO    MainThread:1584 [wandb_init.py:init():505] got version response 
2021-08-24 02:15:10,213 INFO    MainThread:1584 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-24 02:15:10,842 INFO    MainThread:1584 [wandb_init.py:init():540] starting run threads in backend
2021-08-24 02:15:15,865 INFO    MainThread:1584 [wandb_run.py:_console_start():1584] atexit reg
2021-08-24 02:15:15,890 INFO    MainThread:1584 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-24 02:15:15,890 INFO    MainThread:1584 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-24 02:15:15,893 INFO    MainThread:1584 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-24 02:15:15,893 INFO    MainThread:1584 [wandb_init.py:init():565] run started, returning control to user process
2021-08-24 02:15:15,906 INFO    MainThread:1584 [wandb_setup.py:_flush():69] setting env: {}
2021-08-24 02:15:15,907 INFO    MainThread:1584 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-24 02:15:15,907 INFO    MainThread:1584 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210824_021515-3kdczfnz\logs\debug.log
2021-08-24 02:15:15,907 INFO    MainThread:1584 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210824_021515-3kdczfnz\logs\debug-internal.log
2021-08-24 02:15:15,908 INFO    MainThread:1584 [wandb_init.py:init():375] calling init triggers
2021-08-24 02:15:15,908 INFO    MainThread:1584 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-24 02:15:15,909 INFO    MainThread:1584 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3sr6g6zq
2021-08-24 02:15:15,909 INFO    MainThread:1584 [wandb_run.py:finish():1254] finishing run khushal/whether reconizer/3sr6g6zq
