2021-08-18 18:47:02,531 INFO    MainThread:7952 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 18:47:02,531 INFO    MainThread:7952 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 18:47:02,532 INFO    MainThread:7952 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_184702-31ljyx8g\logs\debug.log
2021-08-18 18:47:02,533 INFO    MainThread:7952 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_184702-31ljyx8g\logs\debug-internal.log
2021-08-18 18:47:02,535 INFO    MainThread:7952 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002AB67594400>
2021-08-18 18:47:02,555 INFO    MainThread:7952 [wandb_init.py:init():375] calling init triggers
2021-08-18 18:47:02,556 INFO    MainThread:7952 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 18:47:02,556 INFO    MainThread:7952 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1sw1mbgf
2021-08-18 18:47:02,557 INFO    MainThread:7952 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/1sw1mbgf
2021-08-18 18:47:02,557 INFO    MainThread:7952 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 18:47:02,558 INFO    MainThread:7952 [wandb_run.py:_restore():1526] restore
2021-08-18 18:47:02,687 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 18:47:02,832 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 18:47:03,461 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-18 18:47:03,778 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:03,882 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:03,984 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,087 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,190 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,292 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,395 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,497 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,599 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19500
}

2021-08-18 18:47:04,703 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6825
  total_bytes: 19500
}

2021-08-18 18:47:04,806 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6825
  total_bytes: 19500
}

2021-08-18 18:47:04,909 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6825
  total_bytes: 19500
}

2021-08-18 18:47:05,012 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,116 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,219 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,323 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,425 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,528 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,631 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:05,734 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:06,517 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:06,622 INFO    MainThread:7952 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19500
  total_bytes: 19500
}

2021-08-18 18:47:08,051 INFO    MainThread:7952 [wandb_run.py:_show_files():1898] logging synced files
2021-08-18 18:47:08,058 INFO    MainThread:7952 [wandb_init.py:init():424] starting backend
2021-08-18 18:47:08,058 INFO    MainThread:7952 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 18:47:08,063 INFO    MainThread:7952 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 18:47:08,218 INFO    MainThread:7952 [backend.py:ensure_launched():139] started backend process with pid: 15772
2021-08-18 18:47:08,219 INFO    MainThread:7952 [wandb_init.py:init():429] backend started and connected
2021-08-18 18:47:08,220 INFO    MainThread:7952 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 18:47:08,220 INFO    MainThread:7952 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 18:47:08,220 INFO    MainThread:7952 [wandb_init.py:init():477] updated telemetry
2021-08-18 18:47:08,221 INFO    MainThread:7952 [wandb_init.py:init():500] communicating current version
2021-08-18 18:47:12,305 INFO    MainThread:7952 [wandb_init.py:init():505] got version response 
2021-08-18 18:47:12,305 INFO    MainThread:7952 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 18:47:12,938 INFO    MainThread:7952 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 18:47:17,959 INFO    MainThread:7952 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 18:47:17,961 INFO    MainThread:7952 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 18:47:17,961 INFO    MainThread:7952 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 18:47:17,963 INFO    MainThread:7952 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 18:47:17,963 INFO    MainThread:7952 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 18:47:17,964 INFO    MainThread:7952 [wandb_config.py:__setitem__():141] config set epochs = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002AB676036D0>>
2021-08-18 18:47:17,964 INFO    MainThread:7952 [wandb_run.py:_config_callback():826] config_cb epochs 50 None
2021-08-18 18:47:18,190 INFO    MainThread:7952 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 18:47:18,190 INFO    MainThread:7952 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 18:51:36,024 INFO    MainThread:7952 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 18:51:36,032 INFO    MainThread:7952 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 18:51:36,033 INFO    MainThread:7952 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 18:54:34,213 INFO    MainThread:7952 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 18:54:34,222 INFO    MainThread:7952 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 18:54:34,223 INFO    MainThread:7952 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 18:55:08,326 INFO    MainThread:7952 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 18:55:08,340 INFO    MainThread:7952 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 18:55:08,340 INFO    MainThread:7952 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 18:56:02,849 INFO    MainThread:7952 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 18:56:03,189 INFO    MainThread:7952 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 18:56:03,189 INFO    MainThread:7952 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 18:56:13,815 INFO    MainThread:7952 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 18:56:13,871 INFO    MainThread:7952 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 18:56:13,871 INFO    MainThread:7952 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 18:56:13,871 INFO    MainThread:7952 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_185613-3hf6djar\logs\debug.log
2021-08-18 18:56:13,872 INFO    MainThread:7952 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_185613-3hf6djar\logs\debug-internal.log
2021-08-18 18:56:13,873 INFO    MainThread:7952 [wandb_init.py:init():375] calling init triggers
2021-08-18 18:56:13,873 INFO    MainThread:7952 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 18:56:13,902 INFO    MainThread:7952 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 31ljyx8g
2021-08-18 18:56:13,903 INFO    MainThread:7952 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/31ljyx8g
