2021-08-18 13:40:38,078 INFO    MainThread:11556 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 13:40:38,078 INFO    MainThread:11556 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 13:40:38,079 INFO    MainThread:11556 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_134038-2o4vl6mp\logs\debug.log
2021-08-18 13:40:38,080 INFO    MainThread:11556 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_134038-2o4vl6mp\logs\debug-internal.log
2021-08-18 13:40:38,082 INFO    MainThread:11556 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D085395DC0>
2021-08-18 13:40:38,084 INFO    MainThread:11556 [wandb_init.py:init():375] calling init triggers
2021-08-18 13:40:38,084 INFO    MainThread:11556 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 13:40:38,084 INFO    MainThread:11556 [wandb_init.py:init():424] starting backend
2021-08-18 13:40:38,084 INFO    MainThread:11556 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 13:40:38,105 INFO    MainThread:11556 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 13:40:38,404 INFO    MainThread:11556 [backend.py:ensure_launched():139] started backend process with pid: 10892
2021-08-18 13:40:38,406 INFO    MainThread:11556 [wandb_init.py:init():429] backend started and connected
2021-08-18 13:40:38,408 INFO    MainThread:11556 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 13:40:38,412 INFO    MainThread:11556 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 13:40:38,412 INFO    MainThread:11556 [wandb_init.py:init():477] updated telemetry
2021-08-18 13:40:38,414 INFO    MainThread:11556 [wandb_init.py:init():500] communicating current version
2021-08-18 13:40:43,416 INFO    MainThread:11556 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 13:40:51,371 INFO    MainThread:11556 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 13:40:56,403 INFO    MainThread:11556 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 13:40:56,406 INFO    MainThread:11556 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 13:40:56,407 INFO    MainThread:11556 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 13:40:56,413 INFO    MainThread:11556 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 13:40:56,413 INFO    MainThread:11556 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 13:40:56,414 INFO    MainThread:11556 [wandb_config.py:__setitem__():141] config set epochs = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D08E8730A0>>
2021-08-18 13:40:56,414 INFO    MainThread:11556 [wandb_run.py:_config_callback():826] config_cb epochs 50 None
2021-08-18 14:14:24,983 INFO    MainThread:11556 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:14:25,005 INFO    MainThread:11556 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:14:26,286 INFO    MainThread:11556 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:14:26,340 INFO    MainThread:11556 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 14:14:26,340 INFO    MainThread:11556 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:14:26,341 INFO    MainThread:11556 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_141426-1y7acqgg\logs\debug.log
2021-08-18 14:14:26,341 INFO    MainThread:11556 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_141426-1y7acqgg\logs\debug-internal.log
2021-08-18 14:14:26,343 INFO    MainThread:11556 [wandb_init.py:init():375] calling init triggers
2021-08-18 14:14:26,344 INFO    MainThread:11556 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'momentum': 0.2, 'architecture': 'CNN', 'dataset_id': 'peds-0192', 'infra': 'AWS'}
2021-08-18 14:14:26,370 INFO    MainThread:11556 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2o4vl6mp
2021-08-18 14:14:26,371 INFO    MainThread:11556 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/2o4vl6mp
