2021-09-01 02:26:27,444 INFO    MainThread:21588 [wandb_setup.py:_flush():69] setting env: {}
2021-09-01 02:26:27,444 INFO    MainThread:21588 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-01 02:26:27,445 INFO    MainThread:21588 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-01 02:26:27,445 INFO    MainThread:21588 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210901_022627-2v9z8qtk\logs\debug.log
2021-09-01 02:26:27,445 INFO    MainThread:21588 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210901_022627-2v9z8qtk\logs\debug-internal.log
2021-09-01 02:26:27,446 INFO    MainThread:21588 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000017813A22910>
2021-09-01 02:26:27,448 INFO    MainThread:21588 [wandb_init.py:init():375] calling init triggers
2021-09-01 02:26:27,448 INFO    MainThread:21588 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-01 02:26:27,448 INFO    MainThread:21588 [wandb_init.py:init():424] starting backend
2021-09-01 02:26:27,448 INFO    MainThread:21588 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-01 02:26:27,452 INFO    MainThread:21588 [backend.py:ensure_launched():135] starting backend process...
2021-09-01 02:26:27,581 INFO    MainThread:21588 [backend.py:ensure_launched():139] started backend process with pid: 23204
2021-09-01 02:26:27,582 INFO    MainThread:21588 [wandb_init.py:init():429] backend started and connected
2021-09-01 02:26:27,583 INFO    MainThread:21588 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-09-01 02:26:27,583 INFO    MainThread:21588 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-01 02:26:27,583 INFO    MainThread:21588 [wandb_init.py:init():477] updated telemetry
2021-09-01 02:26:27,584 INFO    MainThread:21588 [wandb_init.py:init():500] communicating current version
2021-09-01 02:26:32,437 INFO    MainThread:21588 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-01 02:26:32,438 INFO    MainThread:21588 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-01 02:26:34,206 INFO    MainThread:21588 [wandb_init.py:init():540] starting run threads in backend
2021-09-01 02:26:39,220 INFO    MainThread:21588 [wandb_run.py:_console_start():1584] atexit reg
2021-09-01 02:26:39,221 INFO    MainThread:21588 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-09-01 02:26:39,222 INFO    MainThread:21588 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-09-01 02:26:39,224 INFO    MainThread:21588 [wandb_run.py:_redirect():1519] Redirects installed.
2021-09-01 02:26:39,224 INFO    MainThread:21588 [wandb_init.py:init():565] run started, returning control to user process
2021-09-01 02:27:59,076 INFO    MainThread:21588 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-01 02:27:59,077 INFO    MainThread:21588 [jupyter.py:save_ipynb():284] not saving jupyter notebook
